define schema DCM_DEMO_2_FINANCE{{env_suffix}}.GOLD;


-- Create aggregate market history fact table
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.GOLD.FACT_MARKET_HISTORY
target_lag='1 hour' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}'
data_metric_schedule = 'TRIGGER_ON_CHANGES'
as
select 
    FMHT.SK_SECURITY_ID,
    FMHT.SK_COMPANY_ID,
    FMHT.SK_DATE_ID,
    FMHT.YIELD,
    FMHT.CLOSE_PRICE,
    FMHT.DAY_HIGH,
    FMHT.DAY_LOW,
    FMHT.VOLUME,
    coalesce(FMHT.CLOSE_PRICE / DFRYE.ROLL_YEAR_EPS, 0) as PE_RATIO,
    FMHCHL.FIFTY_TWO_WEEK_HIGH,
    FMHCHL.SK_FIFTY_TWO_WEEK_HIGH_DATE,
    FMHCHL.FIFTY_TWO_WEEK_LOW,
    FMHCHL.SK_FIFTY_TWO_WEEK_LOW_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FACT_MARKET_HISTORY_TRANS FMHT
left outer join
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL_ROLL_YEAR_EPS DFRYE 
    on FMHT.SK_COMPANY_ID = DFRYE.SK_COMPANY_ID 
    and YEAR(TO_DATE(FMHT.SK_DATE_ID::STRING, 'YYYYMMDD')) || QUARTER(TO_DATE(FMHT.SK_DATE_ID::STRING, 'YYYYMMDD')) = DFRYE.YEAR_QTR
inner join 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FACT_MARKET_HISTORY_CALC_HIGH_LOW FMHCHL 
    on FMHT.SK_SECURITY_ID = FMHCHL.SK_SECURITY_ID
    and FMHT.SK_DATE_ID = FMHCHL.SK_DATE_ID
;


-- Create Fact Holdings
define view DCM_DEMO_2_FINANCE{{env_suffix}}.GOLD.FACT_HOLDINGS
as
select 
    HH.HH_H_T_ID as TRADE_ID
	, HH.HH_T_ID as CURRENT_TRADE_ID
	, DT.SK_CUSTOMER_ID as SK_CUSTOMER_ID
	, DT.SK_ACCOUNT_ID as SK_ACCOUNT_ID
	, DT.SK_SECURITY_ID as SK_SECURITY_ID
	, DT.SK_COMPANY_ID as SK_COMPANY_ID
	, DT.SK_CLOSE_DATE_ID as SK_DATE_ID
	, DT.SK_CLOSE_TIME_ID as SK_TIME_ID
	, DT.TRADE_PRICE as CURRENT_PRICE
	, HH_AFTER_QTY as CURRENT_HOLDING
from 
    DCM_DEMO_2.RAW.HOLDINGHISTORY_STG HH
inner join
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE DT 
    on HH.HH_T_ID = DT.TRADE_ID
;


-- Union Prospect transactions and customer designation into Fact table
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.GOLD.FACT_PROSPECT 
target_lag='6 hours' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
data_metric_schedule = 'TRIGGER_ON_CHANGES'
as
select 
    FPT.AGENCYID as AGENCY_ID,
	FPT.LASTNAME as LAST_NAME,
	FPT.FIRSTNAME as FIRST_NAME,
	FPT.MIDDLEINITIAL as MIDDLE_INITIAL,
	FPT.GENDER,
	FPT.ADDRESSLINE1 as ADDRESS_LINE1,
	FPT.ADDRESSLINE2 as ADDRESS_LINE2,
	FPT.POSTALCODE as POSTAL_CODE,
	FPT.CITY,
	FPT.STATE,
	FPT.COUNTRY,
	FPT.PHONE,
	FPT.INCOME,
	FPT.NUMBERCARS as NUMBER_CARS,
	FPT.NUMBERCHILDREN as NUMBER_CHILDREN,
	FPT.MARITALSTATUS as MARITAL_STATUS,
	FPT.AGE,
	FPT.CREDITRATING as CREDIT_RATING,
	FPT.OWNORRENTFLAG as OWN_OR_RENT_FLAG,
	FPT.EMPLOYER,
	FPT.NUMBERCREDITCARDS as NUMBER_CREDIT_CARDS,
	FPT.NETWORTH as NET_WORTH,
	array_to_string(array_construct_compact(HIGHVALUE,EXPENSES,BOOMER,MONEYALERT,SPENDER,INHERITED),'+') as MARKETING_NAMEPLATE,
	FPIC.IS_CUSTOMER
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.PROSPECT_TRANS_ODS as FPT
join 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.PROSPECT_ISCUST_ODS FPIC 
    on FPT.AGENCYID = FPIC.AGENCYID
;


-- Fact Cash Balances
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.GOLD.FACT_CASH_BALANCES 
target_lag='3 hours'
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}'
data_metric_schedule = 'TRIGGER_ON_CHANGES'
AS
select 
    DA.SK_CUSTOMER_ID
	, DA.SK_ACCOUNT_ID
	, DD.DATE_ID AS SK_DATE_ID
	, SUM(CT.CT_AMT) OVER (PARTITION BY DA.SK_ACCOUNT_ID ORDER BY DD.DATE_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CASH
from 
    DCM_DEMO_2.RAW.CASHTRANSACTION_STG CT 
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_ACCOUNT DA 
    ON CT.CT_CA_ID = DA.ACCOUNT_ID 
    AND CT.CT_DTS BETWEEN DA.SC2_START_DATE 
    AND COALESCE(SC2_END_DATE,'2999-12-31')
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE DD 
    ON DATE_TRUNC('DAY', CT.CT_DTS) = DD.DATE_VALUE::date
;