define database DCM_DEMO_2;
define schema DCM_DEMO_2.RAW;

define table DCM_DEMO_2.RAW.ACCOUNT_STG (
	CDC_FLAG VARCHAR(1) comment 'I OR U DENOTES INSERT OR UPDATE',
	CDC_DSN TIMESTAMP_NTZ(9) comment 'DATABASE SEQUENCE NUMBER',
	CA_ID NUMBER(38,0) comment 'CUSTOMER ACCOUNT IDENTIFIER',
	CA_B_ID NUMBER(38,0) comment 'IDENTIFIER OF THE MANAGING BROKER',
	CA_C_ID NUMBER(38,0) comment 'OWNING CUSTOMER IDENTIFIER',
	CA_NAME VARCHAR(50) comment 'NAME OF CUSTOMER ACCOUNT',
	CA_TAX_ST NUMBER(38,0) comment '0, 1 OR 2 TAX STATUS OF THIS ACCOUNT',
	CA_ST_ID VARCHAR(4) comment 'ACTV OR INAC CUSTOMER STATUS TYPE IDENTIFIER'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;

define table DCM_DEMO_2.RAW.CASHTRANSACTION_STG (
	CDC_FLAG VARCHAR(1) comment 'I DENOTES INSERT',
	CDC_DSN NUMBER(38,0) comment 'DATABASE SEQUENCE NUMBER',
	CT_CA_ID NUMBER(38,0) comment 'CUSTOMER ACCOUNT IDENTIFIER',
	CT_DTS TIMESTAMP_NTZ(9) comment 'TIMESTAMP OF WHEN THE TRADE TOOK PLACE',
	CT_AMT NUMBER(10,2) comment 'AMOUNT OF THE CASH TRANSACTION',
	CT_NAME VARCHAR(100) comment 'TRANSACTION NAME OR DESCRIPTION: E.G. CASH from SALE OF DUPONT STOCK.'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.CUSTOMER_STG (
	CDC_FLAG VARCHAR(1) comment 'DENOTES INSERT OR UPDATE',
	CDC_DSN TIMESTAMP_NTZ(9) comment 'DATABASE SEQUENCE NUMBER',
	C_ID NUMBER(38,0) comment 'CUSTOMER IDENTIFIER',
	C_TAX_ID VARCHAR(20) comment 'CUSTOMER’S TAX IDENTIFIER',
	C_ST_ID VARCHAR(4) comment 'ACTV OR INAC CUSTOMER STATUS TYPE IDENTIFIER',
	C_L_NAME VARCHAR(25) comment 'PRIMARY CUSTOMERS LAST NAME.',
	C_F_NAME VARCHAR(20) comment 'PRIMARY CUSTOMERS FIRST NAME.',
	C_M_NAME VARCHAR(1) comment 'PRIMARY CUSTOMERS MIDDLE INITIAL',
	C_GNDR VARCHAR(1) comment 'GENDER OF THE PRIMARY CUSTOMER',
	C_TIER NUMBER(1,0) comment 'CUSTOMER TIER',
	C_DOB DATE comment 'CUSTOMER’S DATE OF BIRTH, AS YYYY-MM-DD.',
	C_ADLINE1 VARCHAR(80) comment 'ADDRESS LINE 1',
	C_ADLINE2 VARCHAR(80) comment 'ADDRESS LINE 2',
	C_ZIPCODE VARCHAR(12) comment 'ZIP OR POSTAL CODE',
	C_CITY VARCHAR(25) comment 'CITY',
	C_STATE_PROV VARCHAR(20) comment 'STATE OR PROVINCE',
	C_CTRY VARCHAR(24) comment 'COUNTRY',
	C_CTRY_1 VARCHAR(3) comment 'COUNTRY CODE FOR CUSTOMERS PHONE 1.',
	C_AREA_1 VARCHAR(3) comment 'AREA CODE FOR CUSTOMER PHONE 1.',
	C_LOCAL_1 VARCHAR(10) comment 'LOCAL NUMBER FOR CUSTOMERS PHONE 1.',
	C_EXT_1 VARCHAR(5) comment 'EXTENSION NUMBER FOR CUSTOMER PHONE 1.',
	C_CTRY_2 VARCHAR(3) comment 'COUNTRY CODE FOR CUSTOMER PHONE 2.',
	C_AREA_2 VARCHAR(3) comment 'AREA CODE FOR CUSTOMER PHONE 2.',
	C_LOCAL_2 VARCHAR(10) comment 'LOCAL NUMBER FOR CUSTOMER PHONE 2.',
	C_EXT_2 VARCHAR(5) comment 'EXTENSION NUMBER FOR CUSTOMER PHONE 2.',
	C_CTRY_3 VARCHAR(3) comment 'COUNTRY CODE FOR CUSTOMERS PHONE 3.',
	C_AREA_3 VARCHAR(3) comment 'AREA CODE FOR CUSTOMERS PHONE 3.',
	C_LOCAL_3 VARCHAR(10) comment 'LOCAL NUMBER FOR CUSTOMER PHONE 3.',
	C_EXT_3 VARCHAR(5) comment 'EXTENSION NUMBER FOR CUSTOMER PHONE 3.',
	C_EMAIL_1 VARCHAR(50) comment 'CUSTOMERS E-MAIL ADDRESS 1.',
	C_EMAIL_2 VARCHAR(50) comment 'CUSTOMERS E-MAIL ADDRESS 2.',
	C_LCL_TX_ID VARCHAR(4) comment 'CUSTOMERS LOCAL TAX RATE',
	C_NAT_TX_ID VARCHAR(4) comment 'CUSTOMERS NATIONAL TAX RATE'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.DAILYMARKET_STG (
	CDC_FLAG VARCHAR(1) comment 'I DENOTES INSERT',
	CDC_DSN NUMBER(38,0) comment 'DATABASE SEQUENCE NUMBER',
	DM_DATE DATE comment 'DATE OF LAST COMPLETED TRADING DAY.',
	DM_S_SYMB VARCHAR(15) comment 'SECURITY SYMBOL OF THE SECURITY',
	DM_CLOSE NUMBER(8,2) comment 'CLOSING PRICE OF THE SECURITY ON THIS DAY.',
	DM_HIGH NUMBER(8,2) comment 'HIGHEST PRICE FOR THE SECUIRITY ON THIS DAY.',
	DM_LOW NUMBER(8,2) comment 'LOWEST PRICE FOR THE SECURITY ON THIS DAY.',
	DM_VOL NUMBER(38,0) comment 'VOLUME OF THE SECURITY ON THIS DAY.'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.DATE_STG (
	SK_DATEID NUMBER(38,0) comment 'SURROGATE KEY FOR THE DATE',
	DATEVALUE VARCHAR(20) comment 'THE DATE AS TEXT, E.G. 2004-07-07',
	DATEDESC VARCHAR(20) comment 'THE DATE MONTH DAY, YYYY, E.G. JULY 7, 2004',
	CALENDARYEARID NUMBER(4,0) comment 'YEAR NUMBER AS A NUMBER',
	CALENDARYEARDESC VARCHAR(20) comment 'YEAR NUMBER AS TEXT',
	CALENDARQTRID NUMBER(5,0) comment 'QUARTER AS A NUMBER, E.G. 20042',
	CALENDARQTRDESC VARCHAR(20) comment 'QUARTER AS TEXT, E.G. 2004 Q2”',
	CALENDARMONTHID NUMBER(6,0) comment 'MONTH AS A NUMBER, E.G. 20047',
	CALENDARMONTHDESC VARCHAR(20) comment 'MONTH AS TEXT, E.G. 2004 JULY',
	CALENDARWEEKID NUMBER(6,0) comment 'WEEK AS A NUMBER, E.G. 200428',
	CALENDARWEEKDESC VARCHAR(20) comment 'WEEK AS TEXT, E.G. 2004-W28',
	DAYOFWEEKNUM NUMBER(1,0) comment 'DAY OF WEEK AS A NUMBER, E.G. 3',
	DAYOFWEEKDESC VARCHAR(10) comment 'DAY OF WEEK AS TEXT, E.G. WEDNESDAY',
	FISCALYEARID NUMBER(4,0) comment 'FISCAL YEAR AS A NUMBER, E.G. 2005',
	FISCALYEARDESC VARCHAR(20) comment 'FISCAL YEAR AS TEXT, E.G. 2005',
	FISCALQTRID NUMBER(5,0) comment 'FISCAL QUARTER AS A NUMBER, E.G. 20051',
	FISCALQTRDESC VARCHAR(20) comment 'FISCAL QUARTER AS TEXT, E.G. 2005 Q1',
	HOLIDAYFLAG BOOLEAN comment 'INDICATES HOLIDAYS'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.FINWIRE_STG (
	PTS VARCHAR(15) comment 'POSTING DATE & TIME AS YYYYMMDD-HHMMSS - FIN, CMP, SEC',
	REC_TYPE VARCHAR(3) comment 'FIN, CMP, OR SEC - FIN, CMP, SEC',
	COMPANY_NAME VARCHAR(60) comment 'NAME OF THE COMPANY - CMP',
	CIK VARCHAR(10) comment 'COMPANY IDENTIFICATION CODE from SEC - CMP',
	STATUS VARCHAR(4) comment 'ACTV FOR ACTIVE COMPANY, INAC FOR INACTIVE - CMP, SEC',
	INDUSTRY_ID VARCHAR(2) comment 'CODE FOR INDUSTRY SEGMENT - CMP',
	SP_RATING VARCHAR(4) comment 'S&P RATING - CMP',
	FOUNDING_DATE VARCHAR(8) comment 'A DATE AS YYYYMMDD - CMP',
	ADDR_LINE1 VARCHAR(80) comment 'MAILING ADDRESS - CMP',
	ADDR_LINE2 VARCHAR(80) comment 'MAILING ADDRESS - CMP',
	POSTAL_CODE VARCHAR(12) comment 'MAILING ADDRESS - CMP',
	CITY VARCHAR(25) comment 'MAILING ADDRESS - CMP',
	STATE_PROVINCE VARCHAR(20) comment 'MAILING ADDRESS - CMP',
	COUNTRY VARCHAR(24) comment 'MAILING ADDRESS - CMP',
	CEO_NAME VARCHAR(46) comment 'NAME OF COMPANY CEO - CMP',
	DESCRIPTION VARCHAR(150) comment 'DESCRIPTION OF THE COMPANY - CMP',
	YEAR VARCHAR(4) comment 'YEAR OF THE QUARTER END. - FIN',
	QUARTER VARCHAR(1) comment 'QUARTER NUMBER: VALID VALUES ARE 1, 2, 3, 4 - FIN',
	QTR_START_DATE VARCHAR(8) comment 'START DATE OF QUARTER, AS YYYYMMDD - FIN',
	POSTING_DATE VARCHAR(8) comment 'POSTING DATE OF QUARTERLY REPORT AS YYYYMMDD - FIN',
	REVENUE VARCHAR(17) comment 'REPORTED REVENUE FOR THE QUARTER - FIN',
	EARNINGS VARCHAR(17) comment 'NET EARNINGS REPORTED FOR THE QUARTER - FIN',
	EPS VARCHAR(12) comment 'BASIC EARNINGS PER SHARE FOR THE QUARTER - FIN',
	DILUTED_EPS VARCHAR(12) comment 'DILUTED EARNINGS PER SHARE FOR THE QUARTER - FIN',
	MARGIN VARCHAR(12) comment 'PROFIT DIVIDED BY REVENUES FOR THE QUARTER - FIN',
	INVENTORY VARCHAR(17) comment 'VALUE OF INVENTORY ON HAND AT END OF QUARTER - FIN',
	ASSETS VARCHAR(17) comment 'VALUE OF TOTAL ASSETS AT THE END OF QUARTER - FIN',
	LIABILITIES VARCHAR(17) comment 'VALUE OF TOTAL LIABILITIES AT THE END OF QUARTER - FIN',
	SH_OUT VARCHAR(13) comment 'AVERAGE NUMBER OF SHARES OUTSTANDING - FIN, SEC',
	DILUTED_SH_OUT VARCHAR(13) comment 'AVERAGE NUMBER OF SHARES OUTSTANDING (DILUTED) - FIN',
	CO_NAME_OR_CIK VARCHAR(60) comment 'COMPANY CIK NUMBER (IF ONLY DIGITS, 10 VARCHARS) OR NAME (IF NOT ONLY DIGITS, 60 VARCHARS) - FIN, SEC',
	SYMBOL VARCHAR(15) comment 'SECURITY SYMBOL - SEC',
	ISSUE_TYPE VARCHAR(6) comment 'ISSUE TYPE - SEC',
	NAME VARCHAR(70) comment 'SECURITY NAME - SEC',
	EX_ID VARCHAR(6) comment 'ID OF THE EXCHANGE THE SECURITY IS TRADED ON - SEC',
	FIRST_TRADE_DATE VARCHAR(8) comment 'DATE OF FIRST TRADE AS YYYYMMDD - SEC',
	FIRST_TRADE_EXCHG VARCHAR(8) comment 'DATE OF FIRST TRADE ON EXCHANGE AS YYYYMMDD - SEC',
	DIVIDEND VARCHAR(12) comment 'DIVIDEND AS VALUE_T - SEC'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.HOLDINGHISTORY_STG (
	CDC_FLAG VARCHAR(1) comment 'I DENOTES INSERT',
	CDC_DSN NUMBER(38,0) comment 'DATABASE SEQUENCE NUMBER',
	HH_H_T_ID NUMBER(15,0) comment 'TRADE IDENTIFIER OF THE TRADE THAT ORIGINALLY CREATED THE HOLDING ROW.',
	HH_T_ID NUMBER(15,0) comment 'TRADE IDENTIFIER OF THE CURRENT TRADE',
	HH_BEFORE_QTY NUMBER(6,0) comment 'QUANTITY OF THIS SECURITY HELD BEFORE THE MODIFYING TRADE.',
	HH_AFTER_QTY NUMBER(6,0) comment 'QUANTITY OF THIS SECURITY HELD AFTER THE MODIFYING TRADE.'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.HR_STG (
	EMPLOYEEID NUMBER(11,0) comment 'ID OF EMPLOYEE',
	MANAGERID NUMBER(11,0) comment 'ID OF EMPLOYEES MANAGER',
	EMPLOYEEFIRSTNAME VARCHAR(30) comment 'FIRST NAME',
	EMPLOYEELASTNAME VARCHAR(30) comment 'LAST NAME',
	EMPLOYEEMI VARCHAR(1) comment 'MIDDLE INITIAL',
	EMPLOYEEJOBCODE NUMBER(3,0) comment 'NUMERIC JOB CODE',
	EMPLOYEEBRANCH VARCHAR(30) comment 'FACILITY IN WHICH EMPLOYEE HAS OFFICE',
	EMPLOYEEOFFICE VARCHAR(10) comment 'OFFICE NUMBER OR DESCRIPTION',
	EMPLOYEEPHONE VARCHAR(14) comment 'EMPLOYEE PHONE NUMBER'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.INDUSTRY_STG (
	IN_ID VARCHAR(2) comment 'INDUSTRY CODE',
	IN_NAME VARCHAR(50) comment 'INDUSTRY DESCRIPTION',
	IN_SC_ID VARCHAR(4) comment 'SECTOR IDENTIFIER'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.PROSPECT_STG (
	AGENCYID VARCHAR(30) comment 'UNIQUE IDENTIFIER from AGENCY',
	LASTNAME VARCHAR(30) comment 'LAST NAME',
	FIRSTNAME VARCHAR(30) comment 'FIRST NAME',
	MIDDLEINITIAL VARCHAR(1) comment 'MIDDLE INITIAL',
	GENDER VARCHAR(1) comment 'M OR F OR U',
	ADDRESSLINE1 VARCHAR(80) comment 'POSTAL ADDRESS',
	ADDRESSLINE2 VARCHAR(80) comment 'POSTAL ADDRESS',
	POSTALCODE VARCHAR(12) comment 'POSTAL CODE',
	CITY VARCHAR(25) comment 'CITY',
	STATE VARCHAR(20) comment 'STATE OR PROVINCE',
	COUNTRY VARCHAR(24) comment 'POSTAL COUNTRY',
	PHONE VARCHAR(30) comment 'TELEPHONE NUMBER',
	INCOME NUMBER(9,0) comment 'ANNUAL INCOME',
	NUMBERCARS NUMBER(2,0) comment 'CARS OWNED',
	NUMBERCHILDREN NUMBER(2,0) comment 'DEPENDENT CHILDREN',
	MARITALSTATUS VARCHAR(1) comment 'S OR M OR D OR W OR U',
	AGE NUMBER(3,0) comment 'CURRENT AGE',
	CREDITRATING NUMBER(4,0) comment 'NUMERIC RATING',
	OWNORRENTFLAG VARCHAR(1) comment 'O OR R OR U',
	EMPLOYER VARCHAR(30) comment 'NAME OF EMPLOYER',
	NUMBERCREDITCARDS NUMBER(2,0) comment 'CREDIT CARDS',
	NETWORTH NUMBER(12,0) comment 'ESTIMATED TOTAL NET WORTH'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.STATUSTYPE_STG (
	ST_ID VARCHAR(4) comment 'STATUS CODE',
	ST_NAME VARCHAR(10) comment 'STATUS DESCRIPTION'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.TAXRATE_STG (
	TX_ID VARCHAR(4) comment 'TAX RATE CODE',
	TX_NAME VARCHAR(50) comment 'TAX RATE DESCRIPTION',
	TX_RATE NUMBER(6,5) comment 'TAX RATE'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.TIME_STG (
	SK_TIMEID NUMBER(38,0) comment 'SURROGATE KEY FOR THE TIME',
	TIMEVALUE VARCHAR(20) comment 'THE TIME AS TEXT, E.G. 01:23:45',
	HOURID NUMBER(2,0) comment 'HOUR NUMBER AS A NUMBER, E.G. 01',
	HOURDESC VARCHAR(20) comment 'HOUR NUMBER AS TEXT, E.G. 01',
	MINUTEID NUMBER(2,0) comment 'MINUTE AS A NUMBER, E.G. 23',
	MINUTEDESC VARCHAR(20) comment 'MINUTE AS TEXT, E.G. 01:23”',
	SECONDID NUMBER(2,0) comment 'SECOND AS A NUMBER, E.G. 45',
	SECONDDESC VARCHAR(20) comment 'SECOND AS TEXT, E.G. 01:23:45”',
	MARKETHOURSFLAG BOOLEAN comment 'INDICATES A TIME DURING MARKET HOURS',
	OFFICEHOURSFLAG BOOLEAN comment 'INDICATES A TIME DURING OFFICE HOURS'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.TRADEHISTORY_STG (
	TH_T_ID NUMBER(15,0) comment 'TRADE IDENTIFIER. CORRESPONDS TO T_ID IN THE TRADE.TXT FILE',
	TH_DTS TIMESTAMP_NTZ(9) comment 'WHEN THE TRADE HISTORY WAS UPDATED.',
	TH_ST_ID VARCHAR(4) comment 'STATUS TYPE IDENTIFIER.'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.TRADETYPE_STG (
	TT_ID VARCHAR(3) comment 'TRADE TYPE CODE',
	TT_NAME VARCHAR(12) comment 'TRADE TYPE DESCRIPTION',
	TT_IS_SELL NUMBER(38,0) comment 'FLAG INDICATING A SALE',
	TT_IS_MRKT NUMBER(38,0) comment 'FLAG INDICATING A MARKET ORDER'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.TRADE_STG (
	CDC_FLAG VARCHAR(1) comment 'I, U DENOTES INSERT, UPDATE',
	CDC_DSN NUMBER(12,0) comment 'DATABASE SEQUENCE NUMBER',
	T_ID NUMBER(15,0) comment 'TRADE IDENTIFIER.',
	T_DTS TIMESTAMP_NTZ(9) comment 'DATE AND TIME OF TRADE.',
	T_ST_ID VARCHAR(4) comment 'STATUS TYPE IDENTIFIER',
	T_TT_ID VARCHAR(3) comment 'TRADE TYPE IDENTIFIER',
	T_IS_CASH NUMBER(38,0) comment 'IS THIS TRADE A CASH (1) OR MARGIN (0) TRADE?',
	T_S_SYMB VARCHAR(15) comment 'SECURITY SYMBOL OF THE SECURITY',
	T_QTY NUMBER(6,0) comment 'QUANTITY OF SECURITIES TRADED.',
	T_BID_PRICE NUMBER(8,2) comment 'THE REQUESTED UNIT PRICE.',
	T_CA_ID NUMBER(11,0) comment 'CUSTOMER ACCOUNT IDENTIFIER.',
	T_EXEC_NAME VARCHAR(49) comment 'NAME OF THE PERSON EXECUTING THE TRADE.',
	T_TRADE_PRICE NUMBER(8,2) comment 'UNIT PRICE AT WHICH THE SECURITY WAS TRADED.',
	T_CHRG NUMBER(10,2) comment 'FEE CHARGED FOR PLACING THIS TRADE REQUEST.',
	T_COMM NUMBER(10,2) comment 'COMMISSION EARNED ON THIS TRADE',
	T_TAX NUMBER(10,2) comment 'AMOUNT OF TAX DUE ON THIS TRADE'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;


define table DCM_DEMO_2.RAW.WATCH_HISTORY_STG (
	CDC_FLAG VARCHAR(1) comment 'I, U DENOTES INSERT, UPDATE',
	CDC_DSN NUMBER(38,0) comment 'DATABASE SEQUENCE NUMBER',
	W_C_ID NUMBER(11,0) comment 'CUSTOMER IDENTIFIER',
	W_S_SYMB VARCHAR(15) comment 'SYMBOL OF THE SECURITY TO WATCH',
	W_DTS TIMESTAMP_NTZ(9) comment 'DATE AND TIME STAMP FOR THE ACTION',
	W_ACTION VARCHAR(4) comment 'WHETHER ACTIVATING OR CANCELING THE WATCH'
)
change_tracking = TRUE
data_metric_schedule = 'TRIGGER_ON_CHANGES'
;
