define schema DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER;


-- Create DT's to split FINWIRE stage into Company, Financial, and Security tables
-- Company Stage, which just does filtering and column definition
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_CMP_STG 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
data_metric_schedule = 'TRIGGER_ON_CHANGES'
AS
select 
    TO_TIMESTAMP_NTZ(PTS,'YYYYMMDD-HH24MISS') AS PTS
	, REC_TYPE
	, COMPANY_NAME
	, CIK
	, STATUS
	, INDUSTRY_ID
	, SP_RATING
	, TRY_TO_DATE(FOUNDING_DATE) AS FOUNDING_DATE
	, ADDR_LINE1
	, ADDR_LINE2
	, POSTAL_CODE
	, CITY
	, STATE_PROVINCE
	, COUNTRY
	, CEO_NAME
	, DESCRIPTION
from 
    DCM_DEMO_2.RAW.FINWIRE_STG
where 
    REC_TYPE = 'CMP'
;



   
-- Financials Stage, which just does filtering and column definition
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_STG 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
data_metric_schedule = 'TRIGGER_ON_CHANGES'
as
select 
    TO_TIMESTAMP_NTZ(PTS,'YYYYMMDD-HH24MISS') AS PTS
	, REC_TYPE
	, TO_NUMBER(YEAR,4,0) AS YEAR
	, TO_NUMBER(QUARTER,1,0) AS QUARTER
	, TO_DATE(QTR_START_DATE, 'YYYYMMDD') AS QTR_START_DATE
	, TO_DATE(POSTING_DATE, 'YYYYMMDD') AS POSTING_DATE
	, TO_NUMBER(REVENUE,15,2) AS REVENUE
	, TO_NUMBER(EARNINGS,15,2) AS EARNINGS
	, TO_NUMBER(EPS,10,2) AS EPS
	, TO_NUMBER(DILUTED_EPS,10,2) AS DILUTED_EPS
	, TO_NUMBER(MARGIN,10,2) AS MARGIN
	, TO_NUMBER(INVENTORY,15,2) AS INVENTORY
	, TO_NUMBER(ASSETS,15,2) AS ASSETS
	, TO_NUMBER(LIABILITIES,15,2) AS LIABILITIES
	, TO_NUMBER(SH_OUT,13,0) AS SH_OUT
	, TO_NUMBER(DILUTED_SH_OUT,13,0) AS DILUTED_SH_OUT
	, CO_NAME_OR_CIK 
from 
    DCM_DEMO_2.RAW.FINWIRE_STG
where 
    REC_TYPE = 'FIN'
;




-- Securities Stage, which just does filtering and column definition
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_STG 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    TO_TIMESTAMP_NTZ(PTS,'YYYYMMDD-HH24MISS') AS PTS
	, REC_TYPE
	, SYMBOL
	, ISSUE_TYPE
	, STATUS
	, NAME
	, EX_ID
	, TO_NUMBER(SH_OUT,13,0) AS SH_OUT
	, TO_DATE(FIRST_TRADE_DATE,'YYYYMMDD') AS FIRST_TRADE_DATE
	, TO_DATE(FIRST_TRADE_EXCHG,'YYYYMMDD') AS FIRST_TRADE_EXCHG
	, TO_NUMBER(DIVIDEND,10,2) AS DIVIDEND
	, CO_NAME_OR_CIK
from 
    DCM_DEMO_2.RAW.FINWIRE_STG
where 
    REC_TYPE = 'SEC'
;



-- Company ODS, which grabs the latest record for each CIK (not using window function)
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_CMP_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    PTS
	, REC_TYPE
	, COMPANY_NAME
	, CIK
	, STATUS
	, INDUSTRY_ID
	, SP_RATING
	, FOUNDING_DATE
	, ADDR_LINE1
	, ADDR_LINE2
	, POSTAL_CODE
	, CITY
	, STATE_PROVINCE
	, COUNTRY
	, CEO_NAME
	, DESCRIPTION
	, PTS AS SC2_START_DATE
	, LEAD(PTS) OVER (PARTITION BY CIK ORDER BY PTS ASC) AS SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_CMP_STG;


    
-- Financials CIK ODS, selecting rows where CO_NAME_OR_CIK is a CIK
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_CIK_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    PTS
	, REC_TYPE
	, YEAR
	, QUARTER
	, QTR_START_DATE
	, POSTING_DATE
	, REVENUE
	, EARNINGS
	, EPS
	, DILUTED_EPS
	, MARGIN
	, INVENTORY
	, ASSETS
	, LIABILITIES
	, SH_OUT
	, DILUTED_SH_OUT
	, CO_NAME_OR_CIK AS CIK
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_STG
where 
    TRY_TO_NUMBER(CO_NAME_OR_CIK) IS NOT NULL;



    
-- Financials Name ODS, selecting rows where CO_NAME_OR_CIK is a CO_NAME  
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_NAME_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    PTS
	, REC_TYPE
	, YEAR
	, QUARTER
	, QTR_START_DATE
	, POSTING_DATE
	, REVENUE
	, EARNINGS
	, EPS
	, DILUTED_EPS
	, MARGIN
	, INVENTORY
	, ASSETS
	, LIABILITIES
	, SH_OUT
	, DILUTED_SH_OUT
	, CO_NAME_OR_CIK AS NAME
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_STG
where 
    TRY_TO_NUMBER(CO_NAME_OR_CIK) IS NULL
;

    


    
-- Securities CIK ODS, selecting the latest rows where CO_NAME_OR_CIK is a CIK
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_CIK_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    PTS
	, REC_TYPE
	, SYMBOL
	, ISSUE_TYPE
	, STATUS
	, NAME
	, EX_ID
	, SH_OUT
	, FIRST_TRADE_DATE
	, FIRST_TRADE_EXCHG
	, DIVIDEND
	, CO_NAME_OR_CIK AS CIK
	, PTS AS SC2_START_DATE
	, LEAD(PTS) OVER (PARTITION BY SYMBOL ORDER BY PTS ASC) AS SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_STG
where 
    TRY_TO_NUMBER(CO_NAME_OR_CIK) IS NOT NULL
;

    
-- Securities Name ODS, selecting the latest rows where CO_NAME_OR_CIK is a CO_NAME
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_NAME_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    PTS
	, REC_TYPE
	, SYMBOL
	, ISSUE_TYPE
	, STATUS
	, NAME
	, EX_ID
	, SH_OUT
	, FIRST_TRADE_DATE
	, FIRST_TRADE_EXCHG
	, DIVIDEND
	, CO_NAME_OR_CIK AS CO_NAME
	, PTS AS SC2_START_DATE
	, LEAD(PTS) OVER (PARTITION BY SYMBOL ORDER BY PTS ASC) AS SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_STG
where 
    TRY_TO_NUMBER(CO_NAME_OR_CIK) IS NULL;



  
-- Customer ODS, which pulls forward sparse values from prior C_ID rows using CDC_DSN ordering
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.CUSTOMER_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    CDC_DSN AS PTS
	, C_ID
	, IFNULL(C_TAX_ID, LAG(C_TAX_ID) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_TAX_ID
	, IFNULL(C_ST_ID, LAG(C_ST_ID) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_ST_ID
	, IFNULL(C_L_NAME, LAG(C_L_NAME) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_L_NAME
	, IFNULL(C_F_NAME, LAG(C_F_NAME) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_F_NAME
	, IFNULL(C_M_NAME, LAG(C_M_NAME) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_M_NAME
	, IFNULL(C_GNDR, LAG(C_GNDR) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_GNDR
	, IFNULL(C_TIER, LAG(C_TIER) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_TIER
	, IFNULL(C_DOB, LAG(C_DOB) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_DOB
	, IFNULL(C_ADLINE1, LAG(C_ADLINE1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_ADLINE1
	, IFNULL(C_ADLINE2, LAG(C_ADLINE2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_ADLINE2
	, IFNULL(C_ZIPCODE, LAG(C_ZIPCODE) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_ZIPCODE
	, IFNULL(C_CITY, LAG(C_CITY) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_CITY
	, IFNULL(C_STATE_PROV, LAG(C_STATE_PROV) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_STATE_PROV
	, IFNULL(C_CTRY, LAG(C_CTRY) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_CTRY
	, IFNULL(C_CTRY_1, LAG(C_CTRY_1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_CTRY_1
	, IFNULL(C_AREA_1, LAG(C_AREA_1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_AREA_1
	, IFNULL(C_LOCAL_1, LAG(C_LOCAL_1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_LOCAL_1
	, IFNULL(C_EXT_1, LAG(C_EXT_1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_EXT_1
	, IFNULL(C_CTRY_2, LAG(C_CTRY_2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_CTRY_2
	, IFNULL(C_AREA_2, LAG(C_AREA_2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_AREA_2
	, IFNULL(C_LOCAL_2, LAG(C_LOCAL_2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_LOCAL_2
	, IFNULL(C_EXT_2, LAG(C_EXT_2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_EXT_2
	, IFNULL(C_CTRY_3, LAG(C_CTRY_3) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_CTRY_3
	, IFNULL(C_AREA_3, LAG(C_AREA_3) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_AREA_3
	, IFNULL(C_LOCAL_3, LAG(C_LOCAL_3) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_LOCAL_3
	, IFNULL(C_EXT_3, LAG(C_EXT_3) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_EXT_3
	, IFNULL(C_EMAIL_1, LAG(C_EMAIL_1) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_EMAIL_1
	, IFNULL(C_EMAIL_2, LAG(C_EMAIL_2) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_EMAIL_2
	, IFNULL(C_LCL_TX_ID, LAG(C_LCL_TX_ID) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_LCL_TX_ID
	, IFNULL(C_NAT_TX_ID, LAG(C_NAT_TX_ID) IGNORE NULLS OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC)) AS C_NAT_TX_ID
	, CDC_DSN AS SC2_START_DATE
	, LEAD(CDC_DSN) OVER (PARTITION BY C_ID ORDER BY CDC_DSN ASC) AS SC2_END_DATE
from 
    DCM_DEMO_2.RAW.CUSTOMER_STG;


  
-- Account ODS, which pulls forward sparse values from prior CA_ID rows using CDC_DSN ordering
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.ACCOUNT_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    CDC_DSN AS PTS
	, CA_ID
	, IFNULL(CA_B_ID, LAG(CA_B_ID) IGNORE NULLS OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC)) AS CA_B_ID
	, IFNULL(CA_C_ID, LAG(CA_C_ID) IGNORE NULLS OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC)) AS CA_C_ID
	, IFNULL(CA_NAME, LAG(CA_NAME) IGNORE NULLS OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC)) AS CA_NAME
	, IFNULL(CA_TAX_ST, LAG(CA_TAX_ST) IGNORE NULLS OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC)) AS CA_TAX_ST
	, IFNULL(CA_ST_ID, LAG(CA_ST_ID) IGNORE NULLS OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC)) AS CA_ST_ID
	, CDC_DSN AS SC2_START_DATE
	, LEAD(CDC_DSN) OVER (PARTITION BY CA_ID ORDER BY CDC_DSN ASC) AS SC2_END_DATE
from 
    DCM_DEMO_2.RAW.ACCOUNT_STG 
ORDER BY 
    CA_ID,CDC_DSN
;


   
-- Prospect transactions ODS
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.PROSPECT_TRANS_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
	select AGENCYID
	, LASTNAME
	, FIRSTNAME
	, MIDDLEINITIAL
	, GENDER
	, ADDRESSLINE1
	, ADDRESSLINE2
	, POSTALCODE
	, CITY
	, STATE
	, COUNTRY
	, PHONE
	, INCOME
	, NUMBERCARS
	, NUMBERCHILDREN
	, MARITALSTATUS
	, AGE
	, CREDITRATING
	, OWNORRENTFLAG
	, EMPLOYER
	, NUMBERCREDITCARDS
	, NETWORTH 
	, CASE WHEN NETWORTH > 1000000 OR INCOME > 200000 THEN 'HIGHVALUE' ELSE NULL END AS HIGHVALUE
	, CASE WHEN NUMBERCHILDREN > 3 OR NUMBERCREDITCARDS > 5 THEN 'EXPENSES' ELSE NULL END AS EXPENSES
	, CASE WHEN AGE > 45 THEN 'BOOMER' ELSE NULL END AS BOOMER
	, CASE WHEN INCOME < 50000 OR CREDITRATING < 600 OR NETWORTH < 100000 THEN 'MONEYALERT' ELSE NULL END AS MONEYALERT
	, CASE WHEN NUMBERCARS > 3 OR NUMBERCREDITCARDS > 7 THEN 'SPENDER' ELSE NULL END AS SPENDER
	, CASE WHEN AGE < 25 AND NETWORTH > 1000000 THEN 'INHERITED' ELSE NULL END AS INHERITED
from 
    DCM_DEMO_2.RAW.PROSPECT_STG;


    
-- Identify if a prospect is a customer or not
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.PROSPECT_ISCUST_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    T1.AGENCYID
	, CASE WHEN T2.CUSTOMER_ID IS NULL THEN 'FALSE' ELSE 'TRUE' END AS IS_CUSTOMER
from 
    DCM_DEMO_2.RAW.PROSPECT_STG T1
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER_NOW T2 
    ON UPPER(T1.LASTNAME) = UPPER(T2.LAST_NAME) 
    AND UPPER(T1.FIRSTNAME) = UPPER(T2.FIRST_NAME) 
    AND UPPER(T1.ADDRESSLINE1) = UPPER(T2.ADDRESS_LINE_1) 
    AND UPPER(T1.ADDRESSLINE2) = UPPER(T2.ADDRESS_LINE_2) 
    AND UPPER(T1.POSTALCODE) = UPPER(T2.POSTAL_CODE) 
    AND UPPER(T2.STATUS) = 'ACTV'
;




define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DAILY_MARKET_HIGH_LOWS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    DM_S_SYMB as SYMBOL
    , DIM_DATE.DATE_ID as DATE
    , DM_HIGH as DAY_HIGH
    , DM_LOW as DAY_LOW
    , MAX(DM_HIGH) OVER (PARTITION BY DM_S_SYMB ORDER BY DM_DATE ROWS BETWEEN 364 PRECEDING AND CURRENT ROW) as YEAR_HIGH
    , MIN(DM_LOW) OVER (PARTITION BY DM_S_SYMB ORDER BY DM_DATE ROWS BETWEEN 364 PRECEDING AND CURRENT ROW) as YEAR_LOW
from 
    DCM_DEMO_2.RAW.DAILYMARKET_STG
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE 
    ON DAILYMARKET_STG.DM_DATE = DIM_DATE.DATE_VALUE
ORDER BY 
    1,2
;

        
-- Calculate daily market high low for each symbol
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DAILY_MARKET_HIGH_LOW_CALC 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    GET_HIGHS_LOWS.SYMBOL
	, GET_HIGHS_LOWS.DATE
	, GET_HIGHS_LOWS.DAY_HIGH
	, GET_HIGHS_LOWS.YEAR_HIGH
	, REPLACE(MIN(HIGH.DM_DATE)::STRING,'-')::INT AS EARLIEST_HIGH_DATE
	, GET_HIGHS_LOWS.DAY_LOW
	, GET_HIGHS_LOWS.YEAR_LOW
	, REPLACE(MIN(LOW.DM_DATE)::STRING,'-')::INT AS EARLIEST_LOW_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DAILY_MARKET_HIGH_LOWS GET_HIGHS_LOWS
INNER JOIN 
    DCM_DEMO_2.RAW.DAILYMARKET_STG HIGH
	ON HIGH.DM_S_SYMB = GET_HIGHS_LOWS.SYMBOL 
    AND HIGH.DM_HIGH = GET_HIGHS_LOWS.YEAR_HIGH
INNER JOIN 
    DCM_DEMO_2.RAW.DAILYMARKET_STG LOW
	ON LOW.DM_S_SYMB = GET_HIGHS_LOWS.SYMBOL 
    AND LOW.DM_LOW = GET_HIGHS_LOWS.YEAR_LOW
GROUP BY 
    1,2,3,4,6,7
ORDER BY 
    1,2
;



-------------------------- 



-- Gather market history transactions

define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FACT_MARKET_HISTORY_TRANS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    DIM_SECURITY_NOW.SK_SECURITY_ID as SK_SECURITY_ID
	, DIM_SECURITY_NOW.SK_COMPANY_ID as SK_COMPANY_ID
	, DIM_DATE.DATE_ID as SK_DATE_ID
	, ((DIM_SECURITY_NOW.DIVIDEND / DM_CLOSE) * 100) as YIELD
	, DMS.DM_CLOSE AS CLOSE_PRICE
	, DMS.DM_HIGH AS DAY_HIGH
	, DMS.DM_LOW AS DAY_LOW
	, DMS.DM_VOL AS VOLUME
from 
    DCM_DEMO_2.RAW.DAILYMARKET_STG DMS 
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY_NOW 
    ON DMS.DM_S_SYMB = DIM_SECURITY_NOW.SYMBOL 
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE 
    ON DMS.DM_DATE = DIM_DATE.DATE_VALUE 
ORDER BY 
    3;

    
-- Create detailed market history fact table
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FACT_MARKET_HISTORY_CALC_HIGH_LOW 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    DIM_SECURITY.SK_SECURITY_ID AS SK_SECURITY_ID
	, DIM_DATE.DATE_ID AS SK_DATE_ID
	, DMHLC.YEAR_HIGH AS FIFTY_TWO_WEEK_HIGH
	, DMHLC.EARLIEST_HIGH_DATE AS SK_FIFTY_TWO_WEEK_HIGH_DATE
	, DMHLC.YEAR_LOW AS FIFTY_TWO_WEEK_LOW
	, DMHLC.EARLIEST_LOW_DATE AS SK_FIFTY_TWO_WEEK_LOW_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DAILY_MARKET_HIGH_LOW_CALC DMHLC
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY 
    ON DMHLC.SYMBOL = DIM_SECURITY.SYMBOL
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE 
    ON DMHLC.DATE = DIM_DATE.DATE_ID
ORDER BY 
    3;

    
-- Create Trade ODS table
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.TRADE_ODS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    T.CDC_FLAG
	, T.CDC_DSN
	, T.T_ID
	, T.T_DTS
	, TH.TH_DTS
	, COALESCE(TH.TH_DTS,T.T_DTS) AS DT_DTS
	, T.T_ST_ID
	, TH.TH_ST_ID
	, COALESCE(TH.TH_ST_ID,T.T_ST_ID) AS DT_ST_ID
	, T.T_TT_ID
	, CASE WHEN (COALESCE(TH.TH_ST_ID,T.T_ST_ID) = 'SBMT' AND T.T_TT_ID IN ('TMB','TMS')) OR COALESCE(TH.TH_ST_ID,T.T_ST_ID) = 'PNDG' THEN COALESCE(TH.TH_DTS,T.T_DTS) ELSE NULL END AS CREATE_DTS
	, CASE WHEN COALESCE(TH.TH_ST_ID,T.T_ST_ID) IN ('CMPT','CNCL') THEN COALESCE(TH.TH_DTS,T.T_DTS) ELSE NULL END AS CLOSE_DTS
	, T.T_IS_CASH
	, T.T_S_SYMB
	, T.T_QTY
	, T.T_BID_PRICE
	, T.T_CA_ID
	, T.T_EXEC_NAME
	, T.T_TRADE_PRICE
	, T.T_CHRG
	, T.T_COMM
	, T.T_TAX
from 
    DCM_DEMO_2.RAW.TRADE_STG T
LEFT OUTER JOIN 
    DCM_DEMO_2.RAW.TRADEHISTORY_STG TH 
    ON T.T_ID = TH.TH_T_ID
;




-- Reference tables Date, Time, Industry, Status Type, Trade Type, Tax Rate, Broker
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    SK_DATEID AS DATE_ID
    , DATEVALUE::DATE AS DATE_VALUE
    , DATEDESC AS DATE_DESC
    , CALENDARYEARID AS CALENDAR_YEAR_ID
    , CALENDARYEARDESC AS CALENDAR_YEAR_DESC
    , CALENDARQTRID AS CALENDAR_QTR_ID
    , CALENDARQTRDESC AS CALENDAR_QTR_DESC
    , CALENDARMONTHID AS CALENDAR_MONTH_ID
    , CALENDARMONTHDESC AS CALENDAR_MONTH_DESC
    , CALENDARWEEKID AS CALENDAR_WEEK_ID
    , CALENDARWEEKDESC AS CALENDAR_WEEK_DESC
    , DAYOFWEEKNUM AS DAY_OF_WEEK_NUM
    , DAYOFWEEKDESC AS DAY_OF_WEEK_DESC
    , FISCALYEARID AS FISCAL_YEAR_ID
    , FISCALYEARDESC AS FISCAL_YEAR_DESC
    , FISCALQTRID AS FISCAL_QTR_ID
    , FISCALQTRDESC AS FISCAL_QTR_DESC
    , HOLIDAYFLAG AS HOLIDAY_FLAG
from 
    DCM_DEMO_2.RAW.DATE_STG
;



define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_INDUSTRY 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select
    IN_ID
	, IN_NAME 
from 
    DCM_DEMO_2.RAW.INDUSTRY_STG
;



define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_STATUS_TYPE 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    ST_ID
	, ST_NAME
from 
    DCM_DEMO_2.RAW.STATUSTYPE_STG
;



define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TAX_RATE 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    TX_ID
	, TX_NAME
	, TX_RATE
from 
    DCM_DEMO_2.RAW.TAXRATE_STG
;




define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TIME 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    SK_TIMEID AS TIME_ID
	, TIMEVALUE::TIME AS TIME_VALUE
	, HOURID AS HOUR_ID
	, HOURDESC AS HOUR_DESC
	, MINUTEID AS MINUTE_ID
	, MINUTEDESC AS MINUTE_DESC
	, SECONDID AS SECOND_ID
	, SECONDDESC AS SECOND_DESC
	, MARKETHOURSFLAG AS MARKET_HOURS_FLAG
	, OFFICEHOURSFLAG AS OFFICE_HOURS_FLAG
from 
    DCM_DEMO_2.RAW.TIME_STG
;

define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE_TYPE 
target_lag = 'DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}'
as
select 
    TT_ID
	, TT_NAME
	, TT_IS_SELL
	, TT_IS_MRKT
from 
    DCM_DEMO_2.RAW.TRADETYPE_STG
;



define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_BROKER 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    MD5(EMPLOYEEID::STRING || EMPLOYEEFIRSTNAME || EMPLOYEELASTNAME) AS SK_BROKER_ID
	, EMPLOYEEID AS BROKER_ID
	, MANAGERID AS MANAGER_ID
	, EMPLOYEEFIRSTNAME AS FIRST_NAME
	, EMPLOYEELASTNAME AS LAST_NAME
	, EMPLOYEEMI AS MIDDLE_INITIAL
	, EMPLOYEEBRANCH AS BRANCH
	, EMPLOYEEOFFICE AS OFFICE
	, EMPLOYEEPHONE AS PHONE
from
    DCM_DEMO_2.RAW.HR_STG 
where 
    EMPLOYEEJOBCODE = 314
;




  
-- Dim Company SC1, which represents the most recent entire record for a Company
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY_NOW 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    SK_COMPANY_ID
	, LAST_UPDATE_TS
	, COMPANY_ID
	, STATUS
	, NAME
	, INDUSTRY
	, SP_RATING
	, IS_LOW_GRADE
	, CEO
	, ADDR_LINE1
	, ADDR_LINE2
	, POSTAL_CODE
	, CITY
	, STATE_PROV
	, COUNTRY
	, DESCRIPTION
	, FOUNDING_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY
where
    SC2_END_DATE IS NULL
;


    
-- Dim Financials, which unions CIK and NAME ODS tables and does lookup for key
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select DIM_C.SK_COMPANY_ID
	, FIN.YEAR AS FI_YEAR
	, FIN.QUARTER AS FI_QTR
	, FIN.QTR_START_DATE AS FI_QTR_START_DATE
	, FIN.REVENUE AS FI_REVENUE
	, FIN.EARNINGS AS FI_NET_EARN
	, FIN.EPS AS FI_BASIC_EPS
	, FIN.DILUTED_EPS AS FI_DILUT_EPS
	, FIN.MARGIN AS FI_MARGIN
	, FIN.INVENTORY AS FI_INVENTORY
	, FIN.ASSETS AS FI_ASSETS
	, FIN.LIABILITIES AS FI_LIABILITY
	, FIN.SH_OUT AS FI_OUT_BASIC
	, FIN.DILUTED_SH_OUT AS FI_OUT_DILUT
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_NAME_ODS FIN
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY_NOW DIM_C 
    ON DIM_C.NAME = FIN.NAME

UNION ALL 

select DIM_C.SK_COMPANY_ID
	, FIN.YEAR AS FI_YEAR
	, FIN.QUARTER AS FI_QTR
	, FIN.QTR_START_DATE AS FI_QTR_START_DATE
	, FIN.REVENUE AS FI_REVENUE
	, FIN.EARNINGS AS FI_NET_EARN
	, FIN.EPS AS FI_BASIC_EPS
	, FIN.DILUTED_EPS AS FI_DILUT_EPS
	, FIN.MARGIN AS FI_MARGIN
	, FIN.INVENTORY AS FI_INVENTORY
	, FIN.ASSETS AS FI_ASSETS
	, FIN.LIABILITIES AS FI_LIABILITY
	, FIN.SH_OUT AS FI_OUT_BASIC
	, FIN.DILUTED_SH_OUT AS FI_OUT_DILUT
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_FIN_CIK_ODS FIN
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY_NOW DIM_C 
    ON DIM_C.COMPANY_ID = FIN.CIK
;



    
-- Intermediate table that recalculates EPS period line items based on latest data
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL_ROLL_YEAR_EPS_DETAILS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    DIM_F1.SK_COMPANY_ID
	, DIM_F2.SK_COMPANY_ID AS SK_ROLLING_COMPANY_ID
	, DIM_F1.FI_QTR_START_DATE AS FI_ROLLING_PERIOD_END_DATE
	, DIM_F2.FI_QTR_START_DATE
	, DIM_F1.FI_BASIC_EPS
	, DIM_F2.FI_BASIC_EPS AS ROLLING_PERIOD_EPS
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL DIM_F1
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL DIM_F2 
    ON DIM_F1.SK_COMPANY_ID = DIM_F2.SK_COMPANY_ID
	AND DIM_F1.FI_QTR_START_DATE >= DIM_F2.FI_QTR_START_DATE
	AND DIM_F1.FI_QTR_START_DATE <= DATEADD(quarter,3,DIM_F2.FI_QTR_START_DATE)
ORDER BY 
    1,3,4
;


    
-- Intermediate table that recalculates rolling year EPS based on latest data
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL_ROLL_YEAR_EPS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    SK_COMPANY_ID
	, YEAR(FI_ROLLING_PERIOD_END_DATE)::STRING || QUARTER(FI_ROLLING_PERIOD_END_DATE)::STRING AS YEAR_QTR
	, SUM(ROLLING_PERIOD_EPS) AS ROLL_YEAR_EPS 
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_FINANCIAL_ROLL_YEAR_EPS_DETAILS
GROUP BY
    1,2 
ORDER BY 
    1,2
;



    
-- Dim Securities SC2, which unions CIK and NAME ODS tables, does lookups, and generates surrogate key
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    MD5(FIN.SYMBOL || DATE_PART(epoch_second, FIN.PTS)::STRING) AS SK_SECURITY_ID
	, FIN.SYMBOL
	, FIN.PTS AS LAST_UPDATE_TS
	, FIN.ISSUE_TYPE AS ISSUE
	, ST.ST_NAME AS STATUS
	, FIN.NAME
	, FIN.EX_ID AS EXCHANGE_ID
	, DIM_C.SK_COMPANY_ID AS SK_COMPANY_ID
	, FIN.SH_OUT AS SHARES_OUTSTANDING
	, FIN.FIRST_TRADE_DATE AS FIRST_TRADE
	, FIN.FIRST_TRADE_EXCHG AS FIRST_TRADE_ON_EXCHANGE
	, FIN.DIVIDEND
	, FIN.SC2_START_DATE
	, FIN.SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_CIK_ODS FIN
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_STATUS_TYPE ST 
    ON FIN.STATUS = ST.ST_ID
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY_NOW DIM_C 
    ON FIN.CIK = DIM_C.COMPANY_ID

UNION ALL
	
select 
    MD5(FIN.SYMBOL || DATE_PART(epoch_second, FIN.PTS)::STRING) AS SK_SECURITY_ID
	, FIN.SYMBOL
	, FIN.PTS AS LAST_UPDATE_TS
	, FIN.ISSUE_TYPE AS ISSUE
	, ST.ST_NAME AS STATUS
	, FIN.NAME
	, FIN.EX_ID AS EXCHANGE_ID
	, DIM_C.SK_COMPANY_ID AS SK_COMPANY_ID
	, FIN.SH_OUT AS SHARES_OUTSTANDING
	, FIN.FIRST_TRADE_DATE AS FIRST_TRADE
	, FIN.FIRST_TRADE_EXCHG AS FIRST_TRADE_ON_EXCHANGE
	, FIN.DIVIDEND
	, FIN.SC2_START_DATE
	, FIN.SC2_END_DATE  
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_SEC_NAME_ODS FIN
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_STATUS_TYPE ST 
    ON FIN.STATUS = ST.ST_ID
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY_NOW DIM_C 
    ON FIN.CO_NAME = DIM_C.NAME
;



    
-- Dim Security SC1, which represents the most recent entire record for a Security
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY_NOW 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    SK_SECURITY_ID
	, SYMBOL
	, LAST_UPDATE_TS
	, ISSUE
	, STATUS
	, NAME
	, EXCHANGE_ID
	, SK_COMPANY_ID
	, SHARES_OUTSTANDING
	, FIRST_TRADE
	, FIRST_TRADE_ON_EXCHANGE
	, DIVIDEND
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY
where 
    SC2_END_DATE IS NULL;  

  



-- Dim Customer SC2, which transforms certain columns, does lookups, and generates surrogate key	
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    MD5(CNS.C_ID::STRING || DATE_PART(EPOCH_SECOND,CNS.PTS)::STRING) AS SK_CUSTOMER_ID
	, CNS.C_ID AS CUSTOMER_ID
	, CNS.C_TAX_ID AS TAX_ID
	, CNS.C_ST_ID AS STATUS
	, CNS.C_L_NAME AS LAST_NAME
	, CNS.C_F_NAME AS FIRST_NAME
	, CNS.C_M_NAME AS MIDDLE_INITIAL
	, IFF(CNS.C_GNDR IS NULL, NULL, CASE WHEN CNS.C_GNDR = 'M' OR CNS.C_GNDR = 'F' THEN UPPER(CNS.C_GNDR) ELSE 'U' END) AS GENDER
	, CNS.C_TIER AS TIER
	, CNS.C_DOB AS DOB
	, CNS.C_ADLINE1 AS ADDRESS_LINE_1
	, CNS.C_ADLINE2 AS ADDRESS_LINE_2
	, CNS.C_ZIPCODE AS POSTAL_CODE
	, CNS.C_CITY AS CITY
	, CNS.C_STATE_PROV AS STATE_PROV
	, CNS.C_CTRY AS COUNTRY
	, CASE WHEN CNS.C_CTRY_1 != '' AND CNS.C_AREA_1 != '' AND CNS.C_LOCAL_1 != '' THEN CNS.C_CTRY_1 || '-' || CNS.C_AREA_1 || '-' || CNS.C_LOCAL_1 WHEN CNS.C_CTRY_1 = '' AND CNS.C_AREA_1 != '' AND CNS.C_LOCAL_1 != '' THEN CNS.C_AREA_1 || '-' || CNS.C_LOCAL_1 WHEN CNS.C_CTRY_1 = '' AND CNS.C_AREA_1 = '' AND CNS.C_LOCAL_1 != '' THEN CNS.C_LOCAL_1 ELSE NULL END AS PHONE1
	, CASE WHEN CNS.C_CTRY_2 != '' AND CNS.C_AREA_2 != '' AND CNS.C_LOCAL_2 != '' THEN CNS.C_CTRY_2 || '-' || CNS.C_AREA_2 || '-' || CNS.C_LOCAL_2 WHEN CNS.C_CTRY_2 = '' AND CNS.C_AREA_2 != '' AND CNS.C_LOCAL_2 != '' THEN CNS.C_AREA_2 || '-' || CNS.C_LOCAL_2 WHEN CNS.C_CTRY_2 = '' AND CNS.C_AREA_2 = '' AND CNS.C_LOCAL_2 != '' THEN CNS.C_LOCAL_2 ELSE NULL END AS PHONE2
	, CASE WHEN CNS.C_CTRY_3 != '' AND CNS.C_AREA_3 != '' AND CNS.C_LOCAL_3 != '' THEN CNS.C_CTRY_3 || '-' || CNS.C_AREA_3 || '-' || CNS.C_LOCAL_3 WHEN CNS.C_CTRY_3 = '' AND CNS.C_AREA_3 != '' AND CNS.C_LOCAL_3 != '' THEN CNS.C_AREA_3 || '-' || CNS.C_LOCAL_3 WHEN CNS.C_CTRY_3 = '' AND CNS.C_AREA_3 = '' AND CNS.C_LOCAL_3 != '' THEN CNS.C_LOCAL_3 ELSE NULL END AS PHONE3
	, CNS.C_EMAIL_1 AS EMAIL1
	, CNS.C_EMAIL_2 AS EMAIL2
	, NAT_TAX_RATE.TX_NAME AS NATIONAL_TAX_RATE_DESC
	, NAT_TAX_RATE.TX_RATE AS NATIONAL_TAX_RATE
	, LOC_TAX_RATE.TX_NAME AS LOCAL_TAX_RATE_DESC
	, LOC_TAX_RATE.TX_RATE AS LOCAL_TAX_RATE
	, CNS.SC2_START_DATE
	, CNS.SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.CUSTOMER_ODS CNS
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TAX_RATE NAT_TAX_RATE 
    ON CNS.C_NAT_TX_ID = NAT_TAX_RATE.TX_ID 
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TAX_RATE LOC_TAX_RATE 
    ON CNS.C_LCL_TX_ID = LOC_TAX_RATE.TX_ID
;  
    
-- Dim Account SC2, which does lookups and generates surrogate key	
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_ACCOUNT 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
	select MD5(A.CA_ID::STRING || DATE_PART(EPOCH_SECOND,A.PTS)::STRING) AS SK_ACCOUNT_ID
	, A.CA_ID AS ACCOUNT_ID
	, COALESCE(DB.SK_BROKER_ID,'0') AS SK_BROKER_ID 
	, DCN.SK_CUSTOMER_ID AS SK_CUSTOMER_ID
	, A.CA_ST_ID AS STATUS
	, A.CA_NAME AS ACCOUNT_DESC
	, A.CA_TAX_ST AS TAX_STATUS
	, A.SC2_START_DATE
	, A.SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.ACCOUNT_ODS A 
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_BROKER DB 
    ON A.CA_B_ID = DB.BROKER_ID 
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER_NOW DCN 
    ON A.CA_C_ID = DCN.CUSTOMER_ID
;

-- Dim Customer SC1, which represents the most recent entire record for a Customer
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER_NOW 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    SK_CUSTOMER_ID,
	CUSTOMER_ID,
	TAX_ID,
	STATUS,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_INITIAL,
	GENDER,
	TIER,
	DOB,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	POSTAL_CODE,
	CITY,
	STATE_PROV,
	COUNTRY,
	PHONE1,
	PHONE2,
	PHONE3,
	EMAIL1,
	EMAIL2,
	NATIONAL_TAX_RATE_DESC,
	NATIONAL_TAX_RATE,
	LOCAL_TAX_RATE_DESC,
	LOCAL_TAX_RATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER
where 
    SC2_END_DATE is NULL
;


    
-- Dim Account SC1, which represents the most recent entire record for an Account
define view DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_ACCOUNT_NOW 
as
select 
    SK_ACCOUNT_ID,
	ACCOUNT_ID,
	SK_BROKER_ID,
	SK_CUSTOMER_ID,
	STATUS,
	ACCOUNT_DESC,
	TAX_STATUS
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_ACCOUNT
where 
    SC2_END_DATE is NULL
;

    
-- Create Fact Watches
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FACT_WATCHES 
target_lag='10 minutes' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
WITH 
ACTIVE AS (
    select 
        DCN.SK_CUSTOMER_ID AS SK_CUSTOMER_ID
        , DSN.SK_SECURITY_ID AS SK_SECURITY_ID
        , DD.DATE_ID AS SK_DATE_ID_DATE_PLACED
      , NULL AS SK_DATE_ID_DATE_REMOVED
    from 
        DCM_DEMO_2.RAW.WATCH_HISTORY_STG WHS
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER_NOW DCN 
        ON WHS.W_C_ID = DCN.CUSTOMER_ID 
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY_NOW DSN 
        ON WHS.W_S_SYMB = DSN.SYMBOL 
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE DD 
        ON DATE_TRUNC('DAY', WHS.W_DTS) = DD.DATE_VALUE::DATE
    where 
        WHS.W_ACTION = 'ACTV'),
CANCEL AS (
    select 
        DCN.SK_CUSTOMER_ID AS SK_CUSTOMER_ID
        , DSN.SK_SECURITY_ID AS SK_SECURITY_ID
        , NULL AS SK_DATE_ID_DATE_PLACED
        , DD.DATE_ID AS SK_DATE_ID_DATE_REMOVED
    from 
        DCM_DEMO_2.RAW.WATCH_HISTORY_STG WHS
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_CUSTOMER_NOW DCN 
        ON WHS.W_C_ID = DCN.CUSTOMER_ID 
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY_NOW DSN 
        ON WHS.W_S_SYMB = DSN.SYMBOL 
    INNER JOIN 
        DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE DD 
        ON DATE_TRUNC('DAY', WHS.W_DTS) = DD.DATE_VALUE::DATE
    where 
        WHS.W_ACTION = 'CNCL'
        )
select 
    ACTIVE.SK_CUSTOMER_ID
    , ACTIVE.SK_SECURITY_ID
    , ACTIVE.SK_DATE_ID_DATE_PLACED
    , CANCEL.SK_DATE_ID_DATE_REMOVED
from 
    ACTIVE
LEFT OUTER JOIN 
    CANCEL 
    ON ACTIVE.SK_CUSTOMER_ID = CANCEL.SK_CUSTOMER_ID 
    AND ACTIVE.SK_SECURITY_ID = CANCEL.SK_SECURITY_ID
;


    
-- Create Dim Trade Events as SC2
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE_EVENTS 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    TODS.T_ID AS TRADE_ID
	, DA.SK_BROKER_ID AS SK_BROKER_ID
	, TODS.DT_DTS AS TRADE_EVENT_TS
	, IFNULL(CRDD.DATE_ID, LAG(CRDD.DATE_ID) IGNORE NULLS OVER (PARTITION BY TODS.T_ID ORDER BY TODS.DT_DTS ASC)) AS SK_CREATE_DATE_ID
	, IFNULL(CRDT.TIME_ID, LAG(CRDT.TIME_ID) IGNORE NULLS OVER (PARTITION BY TODS.T_ID ORDER BY TODS.DT_DTS ASC)) AS SK_CREATE_TIME_ID
	, CLDD.DATE_ID AS SK_CLOSE_DATE_ID
	, CLDT.TIME_ID SK_CLOSE_TIME_ID
	, DST.ST_NAME AS STATUS
	, DTT.TT_NAME AS TYPE
	, TODS.T_IS_CASH AS CASH_FLAG
	, DS.SK_SECURITY_ID AS SK_SECURITY_ID
	, DS.SK_COMPANY_ID AS SK_COMPANY_ID
	, TODS.T_QTY AS QUANTITY
	, TODS.T_BID_PRICE AS BID_PRICE
	, DA.SK_CUSTOMER_ID AS SK_CUSTOMER_ID
	, DA.SK_ACCOUNT_ID AS SK_ACCOUNT_ID
	, TODS.T_EXEC_NAME AS EXECUTED_BY
	, TODS.T_TRADE_PRICE AS TRADE_PRICE
	, TODS.T_CHRG AS FEE
	, TODS.T_COMM AS COMMISSION
	, TODS.T_TAX AS TAX
	, TODS.DT_DTS AS SC2_START_DATE
	, LEAD(TODS.DT_DTS) OVER (PARTITION BY TODS.T_ID ORDER BY TODS.DT_DTS ASC) AS SC2_END_DATE	
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.TRADE_ODS TODS
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_STATUS_TYPE DST 
    ON TODS.DT_ST_ID = DST.ST_ID
INNER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE_TYPE DTT 
    ON TODS.T_TT_ID = DTT.TT_ID
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE CRDD 
    ON DATE_TRUNC('DAY', TODS.CREATE_DTS) = CRDD.DATE_VALUE
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TIME CRDT 
    ON DATE_TRUNC('SECOND', TO_TIME(TODS.CREATE_DTS)) = CRDT.TIME_VALUE
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_DATE CLDD 
    ON DATE_TRUNC('DAY', TODS.CLOSE_DTS) = CLDD.DATE_VALUE
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TIME CLDT 
    ON DATE_TRUNC('SECOND', TO_TIME(TODS.CLOSE_DTS)) = CLDT.TIME_VALUE
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_ACCOUNT DA 
    ON TODS.T_CA_ID = DA.ACCOUNT_ID 
    AND TODS.DT_DTS BETWEEN DA.SC2_START_DATE 
    AND COALESCE(DA.SC2_END_DATE,'2999-12-31')
LEFT OUTER JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_SECURITY DS 
    ON TODS.T_S_SYMB = DS.SYMBOL
;
    
-- Create Dim Trade as SC1
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE 
target_lag = '2 hours'
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
as
select 
    TRADE_ID
	, SK_BROKER_ID
	, TRADE_EVENT_TS
	, SK_CREATE_DATE_ID
	, SK_CREATE_TIME_ID
	, SK_CLOSE_DATE_ID
	, SK_CLOSE_TIME_ID
	, STATUS
	, TYPE
	, CASH_FLAG
	, SK_SECURITY_ID
	, SK_COMPANY_ID
	, QUANTITY
	, BID_PRICE
	, SK_CUSTOMER_ID
	, SK_ACCOUNT_ID
	, EXECUTED_BY
	, TRADE_PRICE
	, FEE
	, COMMISSION
	, TAX
	, SC2_START_DATE
	, SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_TRADE_EVENTS
where 
    SC2_END_DATE IS NULL
;

    



    
-- Dim Company SC2, which does table lookup, transforms, and surrogate key definition
define dynamic table DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_COMPANY 
target_lag='DOWNSTREAM' 
warehouse='DCM_DEMO_2_FINANCE_WH{{env_suffix}}' 
AS
select 
    MD5(FIN.CIK::STRING || DATE_PART(epoch_second, FIN.PTS)::STRING) AS SK_COMPANY_ID
	, FIN.PTS AS LAST_UPDATE_TS
	, FIN.CIK AS COMPANY_ID
	, DIM_ST.ST_NAME AS STATUS
	, FIN.COMPANY_NAME AS NAME
	, DIM_I.IN_NAME AS INDUSTRY
	, FIN.SP_RATING
	, CASE WHEN (UPPER(SUBSTR(FIN.SP_RATING,1,1)) = 'A' OR UPPER(SUBSTR(FIN.SP_RATING,1,3)) = 'BBB') THEN 0 ELSE 1 END AS IS_LOW_GRADE
	, FIN.CEO_NAME AS CEO
	, FIN.ADDR_LINE1
	, FIN.ADDR_LINE2
	, FIN.POSTAL_CODE
	, FIN.CITY
	, FIN.STATE_PROVINCE AS STATE_PROV
	, FIN.COUNTRY
	, FIN.DESCRIPTION
	, FIN.FOUNDING_DATE
	, FIN.SC2_START_DATE
	, FIN.SC2_END_DATE
from 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.FINWIRE_CMP_ODS FIN
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_STATUS_TYPE DIM_ST 
    ON FIN.STATUS = DIM_ST.ST_ID 
JOIN 
    DCM_DEMO_2_FINANCE{{env_suffix}}.SILVER.DIM_INDUSTRY DIM_I 
    ON FIN.INDUSTRY_ID = DIM_I.IN_ID
; 
